name: Buat APK Kali Linux

on:
  workflow_dispatch: 

jobs:
  build:
    name: Merakit APK
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Source Code
        uses: actions/checkout@v4

      - name: Siapkan Java (Bahan Wajib Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Siapkan NDK Versi Lama
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Beri Akses Gradle
        run: chmod +x ./gradlew

      - name: Mulai Merakit APK (Paksa Jalur NDK)
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: ./gradlew assembleDebug -Pandroid.ndkPath=${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Simpan dan Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Kali-Linux-Mobile
          path: app/build/outputs/apk/debug/*.apk
