name: Buat APK Kali Linux

on:
  workflow_dispatch: 

jobs:
  build:
    name: Merakit APK
    runs-on: ubuntu-22.04 # Menggunakan server yang sedikit lebih stabil untuk aplikasi jadul

    steps:
      - name: Ambil Source Code
        uses: actions/checkout@v4

      - name: Siapkan Java (Bahan Wajib Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Siapkan NDK Versi Lama (Untuk Core Linux)
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          link-to-sdk: true

      - name: Beri Akses Gradle
        run: chmod +x ./gradlew

      - name: Mulai Merakit APK
        run: ./gradlew assembleDebug

      - name: Simpan dan Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Kali-Linux-Mobile
          path: app/build/outputs/apk/debug/*.apk
